---
# tasks file for apache
- name: Install httpd and firewalld
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - "{{packages.web}}"
    - "{{packages.wall}}"
    - python-firewall

- name: start and enable services
  service:
    name: "{{item}}"
    state: started
    enabled: True
  with_items:
    - "{{packages.web}}"
    - "{{packages.wall}}"

- name: Open http firewall port
  firewalld:
    service: "{{rule}}"
    state: enabled
    immediate: True
    permanent: True

- name: Copy template file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html


