---
- name: Block_Rescue
  hosts: localhost 
  tasks:
  - block:
      - name: Install package
        dnf:
          name: xyz
          state: latest

    rescue:

      - name:  Error capture file available at /tmp/package.html
        copy:
          content: "Package is not availabel"
          dest: /tmp/package.html
